### ISSUE TITLE
Static build contains invalid URLs referencing the /src/ directory

### ISSUE THREAD

**Issue by rutzfutz** [bensmithett/tropical#42]
When using your template repo without any modifications and running a build, the resulting file `dist/static/index.html` contains two errors:

1. One of the CSS styles looks like this: `background:url(/src/components/TropicalPhotoButton/gunayala.jpg)`.
  The expected URL here would be something like `/assets/gunayala.f6132071.jpg`.
2. The favicon also contains an invalid URL: `<link data-rh="" rel="icon" type="image/png" href="/src/layouts/favicon.png"/>`
  The expected URL here would be something like `/assets/favicon.1be1fd30.png`.

The errors seem to be caused by module imports not being converted to the correct output URLs during build.

Not sure if it's relevant, but I'm running the build on Windows 10.

**Comment by bensmithett** [comment]
Thanks for the report, I see the same thing. I'll take a look!

**Comment by bensmithett** [comment]
This was introduced in [v10.0.0](https://github.com/bensmithett/tropical/releases/tag/v10.0.0), specifically [the switch to `vite.ssrLoadModule`](https://github.com/bensmithett/tropical/pull/38/files#r796286101) for the build. 

Turns out using ssrLoadModule doesn't result in transformed URLs and [isn't recommended for production builds](https://vitejs.dev/guide/ssr.html#building-for-production) 🙁

I've tried to find an easy way around this, but `type="module"` seems to foil all my attempts. I think I'm going to have to switch back and solve #28 and #35 another way

**Comment by bensmithett** [comment]
Thanks again for reporting this @rutzfutz, it should be fixed in https://github.com/bensmithett/tropical/releases/tag/v10.1.0.

Getting the fix should be a simple merge of upstream changes
